// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson44e6a331DecodeGithubComDiscHighloadcup(in *jlexer.Lexer, out *LocationAvgFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e6a331EncodeGithubComDiscHighloadcup(out *jwriter.Writer, in LocationAvgFilter) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LocationAvgFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e6a331EncodeGithubComDiscHighloadcup(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LocationAvgFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e6a331EncodeGithubComDiscHighloadcup(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LocationAvgFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e6a331DecodeGithubComDiscHighloadcup(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LocationAvgFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e6a331DecodeGithubComDiscHighloadcup(l, v)
}
func easyjson44e6a331DecodeGithubComDiscHighloadcup1(in *jlexer.Lexer, out *LocationAvg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avg":
			out.Avg = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44e6a331EncodeGithubComDiscHighloadcup1(out *jwriter.Writer, in LocationAvg) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"avg\":")
	out.Float64(float64(in.Avg))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LocationAvg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44e6a331EncodeGithubComDiscHighloadcup1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LocationAvg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44e6a331EncodeGithubComDiscHighloadcup1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LocationAvg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44e6a331DecodeGithubComDiscHighloadcup1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LocationAvg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44e6a331DecodeGithubComDiscHighloadcup1(l, v)
}
